language: ruby

rvm:
  - 2.3.4

dist: trusty

addons:
  postgresql: "9.6"

services:
  - postgresql

bundler_args: "--without development --deployment"

cache: bundler

before_script:
  - bin/rake db:create db:schema:load

notifications:
  email: false
